# Generated by Django 2.2.7 on 2019-11-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Restaurant ID')),
                ('Accommodations', models.CharField(default='not set', max_length=300)),
                ('Seating', models.CharField(default='not set', max_length=50)),
                ('Rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentWaitTime', models.IntegerField(default=0)),
                ('PeakWaitTime', models.IntegerField(default=0)),
                ('AveWaitTime', models.IntegerField(default=0)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Review ID')),
                ('Rating', models.IntegerField()),
                ('Reviews', models.CharField(default='none', max_length=300)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Restaurant')),
            ],
        ),
    ]
